#!/bin/bash
#PBS -N Memtest
#PBS -M yx742@nyu.edu
#PBS -m abe
#PBS -l nodes=1:ppn=12,walltime=5:00:00
#PBS -o localhost:${PBS_O_WORKDIR}/
#PBS -e localhost:${PBS_O_WORKDIR}/

module load NYUAD/2.0
module load gcc/4.9.1
module load matlab
cd $PBS_O_WORKDIR

LD_PRELOAD="/share/apps/NYUAD/gcc/gcc/4.9.1/el6/lib/gcc/x86_64-unknown-linux-gnu/4.9.1/libstdc++.so.6" matlab -nodisplay -nosplash -r "a=ones(1e8,34); disp(sum(a(:))) exit"

exit 0;
